### ISSUE TITLE
Вы уже закончили сборку своего прототипа ESP32 SDR?

### ISSUE THREAD

**Issue by Trendyfu** [Cvarc-Xtal/ESP32-SDR-TRX#1]
Здравствуйте, я очень рад видеть ваш проект.Поскольку я не говорю по-русски, следующий текст взят из Google Translate:
Вы сделали печатную плату и завершили тест сборки ESP32 SDR? Есть ли соответствующий видео-сайт для просмотра? Ждем вашего ответа, спасибо.

**Comment by Cvarc-Xtal** [comment]
Здравствуйте!  Google translate хорошо переводит )
Я рад за проявленный интерес к этому проекту.
Этот проект создан для проверки сможет ли ESP32 справиться с обработкой сигналов real-time.
Печатных плат я не делал и не планирую, поскольку схема проекта будет изменена.
Посмотрите на видео по этим ссылкам:
https://www.youtube.com/watch?v=01amlRFFrTA
https://www.youtube.com/shorts/GgdWpgk7hbc
Работа будет продолжена.

**Comment by fupingyi** [comment]
Здравствуйте, Тихонов, я очень рада, что вы так быстро мне ответили.Посмотрел видео по вашей ссылке, и интерфейс у вас очень хороший, очень красивый. Кроме того, я еще проверил ваш файл tayloe.pdf, вроде в нем нет схемы усилителя мощности? Кажется, я не вижу соответствующей трубки усилителя RF. Короче говоря, ваша работа очень интересна, и я надеюсь увидеть полный ESP32 SDR TRX как можно скорее. Ждем Вашего ответа.
73 для вас. я Фу
