### ISSUE TITLE
Дальнейшие планы по этому проекту

### ISSUE THREAD

**Issue by Trendyfu** [Cvarc-Xtal/ESP32-SDR-TRX#2]
Привет
Проект выглядит великолепно, а интерфейс очень приятный.
Можете ли вы рассказать нам о ваших дальнейших шагах?
Также возможно ли связаться с вами по электронной почте? Или есть дискуссионная группа.
73
Trendy

Приведенный выше контент взят из Google Translate

**Comment by Cvarc-Xtal** [comment]
Здравствуйте. Не знаю вашего родного языка, поэтому отвечу на русском.
Пока данный проект в стадии прототипа. Планы по развитию конечно есть. Сначала будут устранены некоторые фундаментальные ошибки (к сожалению они есть). Будет добавлена возможность работы в AM и FM режимах. Будет полностью переделан RF-frontend. Планирую сделать DDC/DUC на недорогих FPGA/ADC/DAC, таких как AD9226 (ADC), AD904 (DAC) и Gowin FPGA. Предарительное моделирование показало неплохие возможности.

**Comment by Trendyfu** [comment]
Спасибо
Я могу перевести русский через Google Translate, так что вам не о чем беспокоиться.
Я новичок в рукоделии и недавно обратил внимание на Wolf SDR, но его стоимость завышена.
Затем я наткнулся на ваш проект, вы проделали отличную работу, ESP32 дешев, это должен быть недорогой проект SDR, звучит потрясающе.
Если вы начнете редизайн, надеюсь, вы сможете более подробно описать его на GitHub.
Если возможно, я буду общаться с вами на английском языке.
Кроме того, есть ли у вас расчетное время для завершения всего проекта? Или время, когда железо изначально формируется.
