### ISSUE TITLE
о сроках реализации этого проекта

### ISSUE THREAD

**Issue by Trendyfu** [Cvarc-Xtal/ESP32-SDR-TRX#3]
Спасибо
Я могу перевести русский через Google Translate, так что вам не о чем беспокоиться.
Я радиолюбитель, недавно обратил внимание на Wolf SDR, но он слишком дорогой.
Затем я наткнулся на ваш проект, вы проделали отличную работу, ESP32 дешев, это должен быть недорогой проект SDR, звучит потрясающе.
Если вы начнете редизайн, надеюсь, вы сможете более подробно описать его на GitHub.
Если возможно, я буду общаться с вами на английском языке позже.
Кроме того, есть ли у вас расчетное время для завершения всего проекта? Или модифицированное время завершения аппаратной схемы.
Большое спасибо за ваши усилия
73

**Comment by jumbo5566** [comment]
> Спасибо Я могу перевести русский через Google Translate, так что вам не о чем беспокоиться. Я радиолюбитель, недавно обратил внимание на Wolf SDR, но он слишком дорогой. Затем я наткнулся на ваш проект, вы проделали отличную работу, ESP32 дешев, это должен быть недорогой проект SDR, звучит потрясающе. Если вы начнете редизайн, надеюсь, вы сможете более подробно описать его на GitHub. Если возможно, я буду общаться с вами на английском языке позже. Кроме того, есть ли у вас расчетное время для завершения всего проекта? Или модифицированное время завершения аппаратной схемы. Большое спасибо за ваши усилия 73

Да, это слишком дорого, поэтому я делаю wolf lite сам, это работает.
